version: '3'
services:
  migrations:
    image: 'mediacms/mediacms:latest'
    container_name: mediacms_migrations
    volumes:
      - 'media_store:/home/mediacms.io/mediacms/media_files/'
      - 'static_store:/home/mediacms.io/mediacms/static/'
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'hsyMqiBVmJYNj8ffX-vW9A'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: 'mediacms_prod'
      DATABASE_PASSWORD: '3se-JZji3guc7E6sf2RMwotanQO0MsJ9'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: 'Asia/Tomsk'
    command: ./deploy/docker/prestart.sh
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  web:
    image: 'mediacms/mediacms:latest'
    container_name: mediacms_web
    ports:
      - '8082:80'
    volumes:
      - 'media_store:/home/mediacms.io/mediacms/media_files/'
      - 'static_store:/home/mediacms.io/mediacms/static/'
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      ENABLE_NGINX: 'yes'
      ENABLE_UWSGI: 'yes'
      FRONTEND_HOST: 'http://localhost'
      PORTAL_NAME: 'MediaCMS'
      SECRET_KEY: 'QO9hrqQDXMboY1FIDt0TEZdXhpFBbcDbc-mEiV1-6IjF3lInK_ZxvauORv6RB7e9EeQ'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: 'mediacms_prod'
      DATABASE_PASSWORD: '3se-JZji3guc7E6sf2RMwotanQO0MsJ9'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: 'Asia/Tomsk'
    restart: unless-stopped
    depends_on:
      - migrations
  celery_beat:
    image: 'mediacms/mediacms:latest'
    container_name: mediacms_celery_beat
    volumes:
      - 'media_store:/home/mediacms.io/mediacms/media_files/'
      - 'static_store:/home/mediacms.io/mediacms/static/'
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'yes'
      ENABLE_MIGRATIONS: 'no'
      SECRET_KEY: 'QO9hrqQDXMboY1FIDt0TEZdXhpFBbcDbc-mEiV1-6IjF3lInK_ZxvauORv6RB7e9EeQ'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: 'mediacms_prod'
      DATABASE_PASSWORD: '3se-JZji3guc7E6sf2RMwotanQO0MsJ9'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: 'Asia/Tomsk'
    restart: unless-stopped
    depends_on:
      - redis
      - migrations
  celery_worker_short:
    image: 'mediacms/mediacms:latest'
    container_name: mediacms_worker_short
    volumes:
      - 'media_store:/home/mediacms.io/mediacms/media_files/'
      - 'static_store:/home/mediacms.io/mediacms/static/'
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'yes'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      SECRET_KEY: 'QO9hrqQDXMboY1FIDt0TEZdXhpFBbcDbc-mEiV1-6IjF3lInK_ZxvauORv6RB7e9EeQ'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: 'mediacms_prod'
      DATABASE_PASSWORD: '3se-JZji3guc7E6sf2RMwotanQO0MsJ9'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: 'Asia/Tomsk'
    restart: unless-stopped
    depends_on:
      - migrations
  celery_worker_long:
    image: 'mediacms/mediacms:latest'
    container_name: mediacms_worker_long
    volumes:
      - 'media_store:/home/mediacms.io/mediacms/media_files/'
      - 'static_store:/home/mediacms.io/mediacms/static/'
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'yes'
      ENABLE_MIGRATIONS: 'no'
      SECRET_KEY: 'QO9hrqQDXMboY1FIDt0TEZdXhpFBbcDbc-mEiV1-6IjF3lInK_ZxvauORv6RB7e9EeQ'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: 'mediacms_prod'
      DATABASE_PASSWORD: '3se-JZji3guc7E6sf2RMwotanQO0MsJ9'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: 'Asia/Tomsk'
    restart: unless-stopped
    depends_on:
      - migrations
  db:
    image: 'postgres:14-alpine'
    container_name: mediacms_db
    volumes:
      - 'mediacms_pg14_data:/var/lib/postgresql/data/'
    restart: always
    environment:
      POSTGRES_USER: 'mediacms_prod'
      POSTGRES_PASSWORD: '3se-JZji3guc7E6sf2RMwotanQO0MsJ9'
      POSTGRES_DB: 'mediacms_prod'
      TZ: 'Asia/Tomsk'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U mediacms_prod'
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:alpine'
    container_name: mediacms_redis
    restart: always
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mediacms_pg14_data:
    driver: local
  media_store:
    driver: local
  static_store:
    driver: local
